# Generated by Django 4.0.4 on 2022-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_rate',
            field=models.IntegerField(default=0),
        ),
    ]
