# Generated by Django 4.0.4 on 2022-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_author_user_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_rate',
            new_name='author_rate',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
    ]
