# Generated by Django 4.0.5 on 2022-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_post_post_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('1', 'Статья'), ('2', 'Новость')], default='1', max_length=2),
        ),
    ]
