# Generated by Django 4.0.5 on 2022-06-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_appointment_appointment_email_alter_appointment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_email',
            new_name='email',
        ),
    ]
