# Generated by Django 4.0.5 on 2022-06-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_appointment_email_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='userName',
            field=models.TextField(default=''),
        ),
    ]
