# Generated by Django 4.0.5 on 2022-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_appointment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysubscribers',
            name='subsEmail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='categorysubscribers',
            name='subsName',
            field=models.TextField(default='user'),
        ),
    ]
