# Generated by Django 4.0.5 on 2022-06-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_categorysubscribers_subsemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysubscribers',
            name='subsEmail',
        ),
        migrations.RemoveField(
            model_name='categorysubscribers',
            name='subsName',
        ),
    ]
