# Generated by Django 4.0.5 on 2022-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_categorysubscribers_subsemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='postID',
            field=models.IntegerField(default=0),
        ),
    ]
